version: '1'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend 
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo:latest
    volumes:
      - db-content:/data/db
    #ports:
      #- "27017:27017"

volumes:
  db-content:


